// export const DEFAULT_INTERNAL_PRECISION = 11;
// export const DEFAULT_DISPLAY_PRECISION = 2;
// export const DEFAULT_LOCALE = 'en-IN';
module.exports = {
	DEFAULT_INTERNAL_PRECISION: 11,
	DEFAULT_DISPLAY_PRECISION: 2,
	DEFAULT_LOCALE: 'en-IN',
};
